<a href="https://colab.research.google.com/github/Cereha/Statistical-methods-of-recognition/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.spatial import ConvexHull

In [4]:
def generate_vectors(N):
    # Генеруємо перші дві координати з параметром 1
    first_two_coords = np.random.exponential(scale=1, size=(N, 2))
    # Генеруємо третю координату також з параметром 1
    third_coord = np.random.exponential(scale=1, size=N)
    # Поєднуємо координати векторів
    vectors = np.column_stack((first_two_coords, third_coord))

    return vectors

def algorithm_of_Cosinec(vectors):
    # Знаходимо опуклу оболонку векторів
    hull = ConvexHull(vectors)
    # Знаходимо нормаль до опуклої оболонки
    normal_to_hull = hull.equations[:, :-1]
    # Обираємо розділяючий вектор, який лежить найбільш паралельно нормалі
    separating_vector = normal_to_hull[np.argmax(np.abs(normal_to_hull[:, 2]))]

    return separating_vector

In [5]:
N = 51
vectors = generate_vectors(N)

# Знаходимо розділяючий вектор з опуклої оболонки за алгоритмом Козинця
separating_vector = cosines_algorithm(vectors)

print("Згенеровані вектори:")
print(vectors)
print("\nРозділяючий вектор:")
print(separating_vector)

Згенеровані вектори:
[[0.8072041  0.53858462 1.2042323 ]
 [0.27535061 2.13999215 3.37399207]
 [3.42069721 1.97383236 1.17971422]
 [0.18779405 1.17141748 0.19870255]
 [1.31507716 0.28543882 0.31143641]
 [0.64219702 1.91596974 0.95084725]
 [0.08348405 1.0730276  0.27012993]
 [0.96553684 1.247492   0.41053484]
 [1.52363289 0.23427465 0.68647537]
 [0.24096325 0.51329219 0.19746048]
 [3.0315746  0.98281718 0.54737487]
 [0.65151025 1.07125618 0.82000368]
 [0.18165709 0.55013402 2.03668513]
 [0.31629742 0.18099401 0.36499571]
 [1.25263281 2.04661092 0.9410885 ]
 [0.27606157 0.3307161  2.43446934]
 [0.1203851  0.34461136 0.87456822]
 [0.93985942 0.5570318  0.32313716]
 [1.04212113 0.32992804 0.17817256]
 [1.03155077 0.1101275  0.13143235]
 [0.28869567 0.66006234 2.56055086]
 [0.15249352 0.21503632 0.49350019]
 [0.27372759 0.5250265  0.76244278]
 [0.88661512 0.1903896  0.55989759]
 [0.06729796 0.75029024 2.68042074]
 [4.32404796 0.83241757 0.91495952]
 [0.03367091 0.42808127 0.80267448]
 [0.717